### ISSUE TITLE
How to help?

### ISSUE THREAD

**Issue by ShadyNawara** [justLV/onju-voice#1]
Hi,
Super cool project, I would love to contribute and that is not just because I am impatient and want access to the early PCB 😃 . In all seriousness, I am an electrical engineer with some circuit design experience and a lot of software experience. Is there any specific tasks you want to tackle first?

**Comment by justLV** [comment]
Thank you!

Off the top of my head, from the software side there could be:

1. Integration into ESP-ADF, to utilize VAD on device instead of on server and make use of both mic's. This may overlap with a discussion here: https://github.com/toverainc/willow/discussions/237
2. Creating a Python script which acts as a dummy device which replicates the basic functionality, so people can use this from a laptop or even Raspberry Pi to test in the interim.

On the hardware side, if you have access to Altium, know the ins and outs of RF, or have any EMC testing experience, I think there could be some work done here. Reason being:
* People don't always have great Wifi so we need to maximize the antenna performance to make sure there aren't issues
* I'm concerned we may have an issue getting this to folks in the EU without this compliance work done
Otherwise take a deep look at the [design files](https://365.altium.com/files/C44B8519-69BA-464B-A221-24D527B89E2C) and lmk if you have any suggestions!

**Comment by ShadyNawara** [comment]
Got it, I can start looking into item 1 since on-device processing seems interesting.
For the python script, not sure I fully understand the use case with all processing being on the server.
for the hardware side, I do have Altium and I can try different antenna designs but would you be able to give me access to download the design files?
For Compliance testing, It isn't something that I am familiar with but I will read up on it and update here if I figured something out.

**Comment by hornej** [comment]
@justLV any reason why you wouldn't just use a module like with a [built-in antenna](https://www.digikey.com/en/products/detail/espressif-systems/ESP32-S3-WROOM-1-N4/16163950?utm_adgroup=&utm_source=google&utm_medium=cpc&utm_campaign=PMax%20Shopping_Product_Medium%20ROAS%20Categories&utm_term=&utm_content=&gclid=Cj0KCQjwoeemBhCfARIsADR2QCsQO_D9zRbp03t2VQMfPURqHo1Y0klZz9__Ya5gFV-ylRM7zQtB91QaAtptEALw_wcB) or [uFL connection](https://www.digikey.com/en/products/detail/espressif-systems/ESP32-S3-WROOM-1U-N4/16163961?utm_adgroup=General&utm_source=google&utm_medium=cpc&utm_campaign=PMax%20Shopping_Product_Zombie%20SKUs&utm_term=&utm_content=General&gclid=Cj0KCQjwoeemBhCfARIsADR2QCt4cZJ6GaxRtiDxB5MSJohj4-Mczts1vraYc5FhvoHk5YQdX2tzuN4aAj-YEALw_wcB)? I shared DigiKey links but they also have them on LCSC.

**Comment by justLV** [comment]
The first proto used one. 

The only one that fit was a MINI, but required placement on the reverse of the PCB and therefore doublesided assembly, as well as cutting away a piece of plastic on the shell.

(There was also a limitation on not having an 8MB PSRAM version which I thought I needed at the time.)

Using a SoC seemed cleaner, easier assembly and more flexibility for PSRAM / flash options

**Comment by austinkregel** [comment]
@justLV Would you be able to export the PCB & Schematics in other formats or for other editors?

I really like what you've built so far and I'd only like to change the layout of the PCB so I can experiment with getting this board to work for the First Gen devices. I'd like to try my hand at keeping all the parts the same but changing the body to match as many different existing platforms as I can.

I've got about a dozen 1st gen Google Home minis around my house, even 2 Google home Maxes, and an OG Google Home.

I unfortunately don't have the money to buy a license with Altium, but I do have experience with KiCad and EasyEDA and believe I could contribute. However I'm running into issues with missing footprints for many of the parts.

**Comment by justLV** [comment]
I don't know what the best way to do this is, are there any importers you can use? If there is a detailed and easy way to export that will help you I can try do this

**Comment by austinkregel** [comment]
It [looks like EasyEDA can import the Altium file](https://prodocs.easyeda.com/en/import-export/import-altium-designer/index.html), but it needs to be saved as a special variant of the Altium file to be able to import it.

Their instructions:

Open the schematic diagram and PCB in Altium Designer, in “File - Save As”, select “altiumvanced Schematic ascii(*.SchDoc)” or “PCB ASCII File(*.PcbDoc)”

![image](https://github.com/justLV/onju-voice/assets/5355937/5584e2c0-4dbb-4101-8e19-b2e437aa39bf)

It also looks like Altium lets you export the footprints as [well based on their doc here](https://www.altium.com/documentation/altium-concord-pro/altium-concord-pro-extracting-data-after-subscription-expiration?version=1.1) 👀 

![image](https://github.com/justLV/onju-voice/assets/5355937/eba38bc0-7755-4eaa-8b9e-6049baf4607f)


Although, the resulting filenames will probably be the same, despite the format changing 😅

**Comment by austinkregel** [comment]
@justLV Have you had any luck exporting the files? 👀 

I keep seeing pings on here for the First Gen Google Home Mini 😆

**Comment by ShadyNawara** [comment]
@austinkregel here is the pcb and schematics exported as ascii pcbdoc and schdoc
[ascii.zip](https://github.com/justLV/onju-voice/files/14227771/ascii.zip)

**Comment by justLV** [comment]
Thank you @ShadyNawara !
