### ISSUE TITLE
Let Elevenlabs use new multilangual v2 model

### ISSUE THREAD

**Issue by jwhengeveld** [justLV/onju-voice#13]
At default, the Elevenlabs API uses the old model. The multilangual model v2 is much better and sounds more natural in other languages (Dutch for me)

Here is the code to change the model. For the file elevenlabs.py around line 61

Before: 
```
 def text_to_speech(self, device, text, path_name="data"):
        now = datetime.now()
        now_str = now.strftime("%Y-%m-%d_%H-%M-%S")
        payload = json.dumps({
            "text": text,
        })

```
After: 
```
 def text_to_speech(self, device, text, path_name="data"):
        now = datetime.now()
        now_str = now.strftime("%Y-%m-%d_%H-%M-%S")
        payload = json.dumps({
            "text": text,
            "model_id": "eleven_multilingual_v2",
        })
```

**Comment by pl0ink** [comment]
Great!  Results in Dutch are much better. :-)

**Comment by justLV** [comment]
Closing, but feel free to make a PR.

New 11labs models & py package are much better so probably would benefit from a major overhaul & using streaming
