### ISSUE TITLE
esphome compatibility?

### ISSUE THREAD

**Issue by 2m** [justLV/onju-voice#14]
esphome is a project that generates firmware for various esp32 microcontroller powered devices from configuration files. This project has recently added [Voice Assistant](https://esphome.io/components/voice_assistant.html) support that uses [I²S Audio](https://esphome.io/components/i2s_audio).

How possible would it be to make esphome firmware work on onju-voice board?

**Comment by kiwipaulrob** [comment]
+ 1

**Comment by bedbug1226** [comment]
Looks like tetele did it already!

https://github.com/justLV/onju-voice/issues/15#issuecomment-1785141052

**Comment by LordNex** [comment]
So now I can just serial flash the boards with ESPHome and use it for updates. Sweet. Can't wait to get my 5 boards in!

**Comment by LordNex** [comment]
So I'm somewhat confused on using PCBWay. I'd prefer to have it get an ESP32-IDF as he suggests to try and make this as close as possible to a slap in replacement for USA users currently running a Home Assistant server with a full Wyoming Protocal Stack and HA’s new conversation pipeline. Not sure if RaspiAudio is going in as well to make this similar to the LUX. If anyone has more expireince than I do who wants to help with a USA order let me know. We already have a group ready for 10 boards.
