### ISSUE TITLE
Home Assistant Media Playback functionality.

### ISSUE THREAD

**Issue by bedbug1226** [justLV/onju-voice#15]
Might be a duplicate of "https://github.com/justLV/onju-voice/issues/14"

Being able to use these board replacements with Home Assistant media playback would also be dope.

Using Home Assistant smart home software.
https://www.home-assistant.io/

Might fit in well with their "Year of the Voice".

I have to run a keep alive script to keep my nest speakers awake and semi synced which mutes, plays 1 second of silence, then unmutes, every 3 minutes.
They always get desynced and they also play the chime whenever an action is done to them other then mute if my script fails. (such as setting volume, play, pause)

Having a way to have all these synced and also not have the activation noise would be so nice and I would replace all the nest boards around my house.

Fingers crossed for boards for the larger nest audio as well.

**Comment by kiwipaulrob** [comment]
+ 1

**Comment by tetele** [comment]
Using the Onju as a media player and voice assistant, all in one https://gist.github.com/tetele/75815c53cfd2a02412ef153f9c2d24e2

**Comment by bedbug1226** [comment]
> Using the Onju as a media player and voice assistant, all in one [gist.github.com/tetele/75815c53cfd2a02412ef153f9c2d24e2](https://gist.github.com/tetele/75815c53cfd2a02412ef153f9c2d24e2)

GREAT!

Will look into this!

**Comment by jmorris644** [comment]
I have done this complete install. It works perfectly!!
