### ISSUE TITLE
Order with JLCPCB?

### ISSUE THREAD

**Issue by ohhai-kthxbai** [justLV/onju-voice#19]
@justLV this project is very exciting, thank you for sharing your work.

Is it possible that you could setup your design for purchase with JLCPCB as you have with PCBWay? I see that you get paid/credit if ordered via PCBWay, and I want that to continue with JLCPCB. I'm trying to find a cheaper supplier, but not cut you out of the deal!

**Comment by justLV** [comment]
Feel free to download the gerbers and order from JLC. I’d had some quality issues with them so didn’t want to recommend it, but I have no issue with people ordering from wherever is best for them

**Comment by ohhai-kthxbai** [comment]
Useful to know about the quality issues. Thanks.

**Comment by haritan** [comment]
@ohhai-kthxbai 
Did you end up doing it in JLCPCB?
