### ISSUE TITLE
OpenvoiceOS and hivemind

### ISSUE THREAD

**Issue by denics** [justLV/onju-voice#2]
Great project, is there a chance to use it as a [hivemind](https://github.com/JarbasHiveMind) client?

**Comment by justLV** [comment]
Hivemind looks interesting! Unfortunately don't know it, but integration should be possible if there is an ESP32 implementation?

Similar to the discussion on [Willow inference server](https://github.com/justLV/onju-voice/discussions/3) synergy, compatibility *should* be a given if it uses the same chipset (ESP32-S3).
