### ISSUE TITLE
Custom PBC support for Google Home Mini 1st gen?

### ISSUE THREAD

**Issue by JanOstrowka** [justLV/onju-voice#20]
Hello,

I'm interested in using a custom PBC with my Google Home Mini 1st gen device. I know the documentation recommends using 2nd gen devices, but since I already have a 1st gen unit, I wanted to check if custom PBC would work on it before purchasing an upgrade.

Does anyone have experience getting custom PBC working on the original Home Mini? Or are there technical limitations that prevent it from being supported?

Any insight would be appreciated. Thanks!

**Comment by LordNex** [comment]
Personally I have not. But I would imagine there might be new holes your had to place to screw it in or just hot glue it in place. As long as the board heat have a circuit lead running through it you can take some wire snips or something similar and try and cut the board to fit. Although I wouldn't do that unless I absolutely had too. 

You might be able to talk to the designer and see if there he could provide you the board schematics. But st that point your getting close to the price and pain that picking up a RaspiAudio Muse LUX would be.

**Comment by justLV** [comment]
All the EE design files are in the repo, feel free to review and compare to the 1st gen dimensions
