### ISSUE TITLE
Onju for Echo dot ?

### ISSUE THREAD

**Issue by nyok92** [justLV/onju-voice#23]
Hi @justLV ,
Is there a PCB version for the Amazon echo dot 5 ?
If not, cloud it be even possible to make one ?
Thanks

**Comment by justLV** [comment]
Nope, sorry. Same answer for all variants(#28 #29 #6 #20 #27 #36) , I won't be building anything new, but feel free to take the ECAD and run with it or work with someone on Upwork etc.

**Comment by gcormier** [comment]
I've started working on one for the Echo Dot v5.
