### ISSUE TITLE
[REQUEST] 3.5mm audio jack/plug (phone connector) as an line input auxiliary port (AUX) for music

### ISSUE THREAD

**Issue by Hedda** [justLV/onju-voice#30]
Please consider adding an optional feature with 3.5mm audio jack/plug (phone connector) as an auxiliary port (AUX) for music input.

The main reason for the request is would love to be able to route and cast that I2S audio stream from that line input with retro analoge music stereo players that do not have built-in audio casting/streaming capabilities, like for example LP record players (turntables), cassette players, Music CD players, Mini-Disc Player, (which for semi-nostalgic and tactile reasons I do not want to just want to record and digitize to stream as FLAC files which many suggests doing instead as a workaround solition).

However not sure if this is technically possible for music input with the built-in ESP32 DAC features without also adding other I2S chip?

e.g. LP record player (turntable) with a preamp -> Onju-Voice with line input AUX port -> ESPHome -> Home Assistant -> [Google Cast](https://www.home-assistant.io/integrations/cast/).

The idea comes from the "Google Home Max" speaker which difference itself by featuring a [3.5mm audio jack (phone connector) as as a line input auxiliary port (which is not the same as a microphone) ](https://producerhive.com/ask-the-hive/line-in-vs-mic-in/)and that enables the "Google Home Max" speaker to also cast Chromecast audio, which uniquely makes it the only commercial hardware appliance that features Chromecast audio casting.

ESPHome i2s_audio component for ESP32 allows for receiving and sending audio via I²S but not sure how well works for line input?

https://esphome.io/components/i2s_audio

This could perhaps be used with an audio casting add-on in Home Assistant like AirCast or similar to cast Chromecast audio or AirPlay?

https://github.com/hassio-addons/addon-aircast

https://github.com/hassio-addons/addon-airsonos

PS: My ultimate goal would be to achieve an open-source multi-room sound system with casting done over some open audio protocol.

**Comment by justLV** [comment]
That sounds great but no longer will be a retrofit of a Nest Mini but a totally different form factor
