### ISSUE TITLE
PCB Conponent issue: BOM in PCBWay

### ISSUE THREAD

**Issue by saya6k** [justLV/onju-voice#33]
[Quotation and problem T-2D6W460623A-10sets-onju-voice-bom(2023-12-11).xls](https://github.com/justLV/onju-voice/files/13634248/Quotation.and.problem.T-2D6W460623A-10sets-onju-voice-bom.2023-12-11.xls)

I got quotation that there was problem in BOM in PCBway.

> Value listed as [0.1W], but part value is [200MW], please confirm which one should we follow?

Which one is correct? Can I use 200MW ohm?

**Comment by gnormandin** [comment]
> I have an order of 10 ready for the US. I can provide the BoMs from PCBway as well as thier commitment to build and ship me 10 for $300.56 USD
> 
> This is my last call before all that work gets canceled as I'm not ordering more than I need without backers. I can use 4-5 board by myself. I was trying to help out. But I don't know what's going on now. So again last call.

Are any of these still available?

**Comment by LordNex** [comment]
> > I have an order of 10 ready for the US. I can provide the BoMs from PCBway as well as thier commitment to build and ship me 10 for $300.56 USD
> 
> > 
> 
> > This is my last call before all that work gets canceled as I'm not ordering more than I need without backers. I can use 4-5 board by myself. I was trying to help out. But I don't know what's going on now. So again last call.
> 
> 
> 
> Are any of these still available?

No I couldn't get enough people to commit and after further review. Doesn't look like it's going to be able to do what I was hoping for anyway. 

So I dropped the order and do t have any plans to move further anytime soon. Sorry
