### ISSUE TITLE
PCB check

### ISSUE THREAD

**Issue by wriede** [justLV/onju-voice#34]
PCBway asked me to verify the component orientation is the attached pictures. Since I have no clue, I'd appreciate help from someone who has working boards. Thanks!
[pleasecheck.zip](https://github.com/justLV/onju-voice/files/13637494/pleasecheck.zip)

**Comment by tom-bourjala** [comment]
You can use the [back PCB picture](https://github.com/justLV/onju-voice/blob/master/images/back_pcb.jpg) from the repo as a reference.

Your leds orientation are conform to the reference image.
