### ISSUE TITLE
(Request) Please Consider Onju Voice PCB for Echo Dot (5) Kids

### ISSUE THREAD

**Issue by firstusing** [justLV/onju-voice#36]
Hey,
First of all thank you, I bought already 5 PCBs of your development. 
The way you think is a great example of Local helpers and self controlled devices. 

I have not the knowledge to recreate the PCB for my kids Echo Dots but I would like to switch them to locally, so if you could spare the time I would appreciate it. 

Thank you for your work!

**Comment by ccMatrix** [comment]
This would be so awesome. Having 100% local control over the content for the kids would be so nice. The echo dot kids probably isn't much different inside than the other echo dot but just a different skin on top.

Creating such a replacement PCB is not an easy task and from what I see it isn't even 100% done yet for the Google Nest one. So it could probably be used as a blueprint but one would still need to figure out how to talk to the hardware provided by Amazon.

**Comment by LukeTowers** [comment]
@justLV would you be open to the community sponsoring you to develop PCBs for echo dots? I have 3rd gen echo dots in basically every room in my house and if there was a similar modification I could make to run them all through Home Assistant instead of Amazon I would in a heartbeat.

@tetele is that something that you'd be able to help with?

**Comment by tetele** [comment]
@LukeTowers the software part, sure. The hardware design part... i'm clueless :)

I also don't own any Alexa devices, but that's the smaller issue here.

**Comment by justLV** [comment]
Sorry I won't be able to do that, doing a design is quite a bit of work and honestly if you're really interested in getting prototypes it most likely will be easier/cheaper to get Nest mini's off of eBay than go through the iteration on a PCB design.
