### ISSUE TITLE
Using a ESP32-C6 instead of S3?

### ISSUE THREAD

**Issue by nightscape** [justLV/onju-voice#4]
Hi Justin, super-interesting project!!
I'm a complete noob w.r.t. hardware development, so forgive me if my question is plain stupid 😉 
Would it be possible to replace the ESP32-S3 with a [ESP32-C6](https://www.espressif.com/en/products/socs/esp32-c6)?
The reason being that the C6 supports Thread, so this would enable Matter over Thread use cases 😃

**Comment by justLV** [comment]
Interesting, I think the focus wasn't specifically on smart home, but rather audio processing.

The S3 does have a dual-core unlike the C6, is fairly common in new projects and is on the latest audio development boards from Espressif, so seems like a great candidate for these reasons.

While ESP-ADF looks like it supports the C6, I'm not sure at first glance if https://github.com/espressif/esp-skainet does.

**Comment by justLV** [comment]
If there is interest from the SW development side on someone building up a fully featured smart home device that makes use of thread, then this should be a fairly easy swap out from the PCB side.

**Comment by ds-sebastian** [comment]
Even if not fully featured, I think it would still be helpful to allow for building a thread mesh since Google Home devices are typically spread out around home.

**Comment by LordNex** [comment]
You considered making CC2674/CC2674P/CC2674R and/or CC1354/CC1354P Zigbee adapters for devs & early-adopters?

Check out this discussion -> Koenkk/Z-Stack-firmware#476

There is no community firmware from Koenkk yet but that is probably partially because no one made a CC2674 or CC1354 adapter yet.

[https://github.com/tube0013/tube_gateways/discussions/161](https://github.com/tube0013/tube_gateways/discussions/161)

**Comment by LordNex** [comment]
> You considered making CC2674/CC2674P/CC2674R and/or CC1354/CC1354P Zigbee adapters for devs & early-adopters?
> 
> Check out this discussion -> Koenkk/Z-Stack-firmware#476
> 
> There is no community firmware from Koenkk yet but that is probably partially because no one made a CC2674 or CC1354 adapter yet.
> 
> [https://github.com/tube0013/tube_gateways/discussions/161](https://github.com/tube0013/tube_gateways/discussions/161)
> 

I've been working with this team on my Zigbee network. It would be interesting if you could add the ability of each Google Home to also be a Zigbee Repeater or Router. Eventually I would imagine it should be thread/matter able with Home Assistant and the right hardware.
