### ISSUE TITLE
How to connect the device to server? 

### ISSUE THREAD

**Issue by shyamvalsan** [justLV/onju-voice#45]
Stupid question I know. But what am I missing here? 

I have the device with custom PCB and firmware loaded. 

I have the server running in the same WiFi network. 

What next?

(I don't have homeassistant running)

**Comment by jimbo601** [comment]
I think that it needs to be able to connect to the ESPHome. Normally this is done in HA, or the smart home program of your choice. I'm referencing this video: https://www.youtube.com/watch?v=xQqhqGd14YY
