### ISSUE TITLE
Out of 5 boards, one seems numb, potential PCB issue debugging

### ISSUE THREAD

**Issue by s00500** [justLV/onju-voice#47]
Hi everyone,

First of all AWESOME PROJECT. I got me boards from pcbway and installing the first device was just pure satisfaction, so easy to get it setup and it instantly worked nicely on my homeassistant setup (using the esphome config)

Then I installed a second one, also working great, but the third one I tried seems numb. I can make it work when I am really close to it and speak loudly, but else it is strange. Do you have any points what to look for on the PCB when debugging ? I would love to not have to throw one out...

So if there is any voltages I can check, components that might be misplaced or anything else you can point me to please let me know. I am kinda used to do PCB debugging and changing out smd components, so that wont be an issue, but any tipps will save me time ;-)

I will still keep posting here in case anyone runs into the same issue as well

**Comment by s00500** [comment]
So I just took the PCB for a quick look and found one of the caps around the voltage regulator to be standing up, after fixing that I could not get an improvement yet though...

**Comment by s00500** [comment]
Hihi ok... I finally found out what was happening... after many hours of debugging I realised that the tape on the mic entry was so badly done that it was actually clogging th mic...

In the process I still fixed the cap (that did not matter too much probably though) and also learned on how to get the voice recordings out of homeassistant (using debug_recording_dir: in the config)

https://www.home-assistant.io/voice_control/troubleshooting/


Here are some pictures, consider this issue closed, may it help others :-)


Thanks again for this awesome PCB design and project !

![IMG_9700](https://github.com/justLV/onju-voice/assets/1556271/7b115890-459c-4e06-b2ad-f72780d95c3a)
![IMG_9711](https://github.com/justLV/onju-voice/assets/1556271/1df079f4-baa7-41e5-b04d-fb5e3b7e9033)
![IMG_9699](https://github.com/justLV/onju-voice/assets/1556271/8b0335fa-f866-41b5-be2b-273bdcf10998)

**Comment by LordNex** [comment]
> Hihi ok... I finally found out what was happening... after many hours of debugging I realised that the tape on the mic entry was so badly done that it was actually clogging th mic...
> 
> 
> 
> In the process I still fixed the cap (that did not matter too much probably though) and also learned on how to get the voice recordings out of homeassistant (using debug_recording_dir: in the config)
> 
> 
> 
> https://www.home-assistant.io/voice_control/troubleshooting/
> 
> 
> 
> 
> 
> Here are some pictures, consider this issue closed, may it help others :-)
> 
> 
> 
> 
> 
> Thanks again for this awesome PCB design and project !
> 
> 
> 
> ![IMG_9700](https://github.com/justLV/onju-voice/assets/1556271/7b115890-459c-4e06-b2ad-f72780d95c3a)
> 
> ![IMG_9711](https://github.com/justLV/onju-voice/assets/1556271/1df079f4-baa7-41e5-b04d-fb5e3b7e9033)
> 
> ![IMG_9699](https://github.com/justLV/onju-voice/assets/1556271/8b0335fa-f866-41b5-be2b-273bdcf10998)
> 
> 
> 
> 
> 
> 

Just curious, how much did that magnifying monitor setup run you? In approx USD? Very nice. I'm. Still using an old handy hand magnifier that I happened to find in an old Hobby Store. And I can't find even parts to replace lost parts for it anymore.

**Comment by jherby2k** [comment]
@s00500 I seem to have the same issue with the mics not working, and 2 different PCBs (so its the enclosure i think). However i can't see what's wrong in your pic or on my device. looking at my working unit, they seem the same also - maybe the black tape is a bit off on one side. tried adjusting it a bit but don't really see how its "wrong" or blocking it. i don't really know what the black tape is for so i'm reluctant to modify it too much. Any pointers?

is it that its tucked up inside the hole behind that post thing? if so, what did you do to fix it? trim it? take the whole black tape off and reapply?

edit: I just pulled the metal dealy out, cut the tape out of the hole from behind, then put it back in. It still can't hear me! I think i'm going crazy. Maybe i have two defective PCBs?

**Comment by s00500** [comment]
Have you had it hear you once even? In general id say just get rid of the tape on the mics, it is just causing issues
