### ISSUE TITLE
QQ - where are the mic's?

### ISSUE THREAD

**Issue by jherby2k** [justLV/onju-voice#48]
Just putting some onjus together right now and I have one unit where I can't get the mic working. Where are the mics anyway? Is it on the board or in the speaker housing?

**Comment by sixtyfive** [comment]
Check out https://raw.githubusercontent.com/justLV/onju-voice/master/images/header_white.jpg ... zoom in on the bottom PCB (the left one of the two on the table) and check the little "mouse ear" protrusions left and right. Each one has a little rectangular device of silver-gold-ish colour, next to it the labels M1 and M2. Those are the MEMS microphones.

Someone else here in the Issues mentioned that the tape in the enclosure was clogging them up.
