### ISSUE TITLE
Media Player does not work

### ISSUE THREAD

**Issue by jchenny7** [justLV/onju-voice#49]
I am having problem playing music through the device in Home Assistant and Music Assistant, the device does not respond at all  after commands been sent, does the Media Player allow to play streaming music?

**Comment by Chaphasilor** [comment]
From the readme:

> it is not intended to be a music playback device

So it's not supported (yet)

**Comment by adoucette** [comment]
In Home Assistant, Music Assistant, I got it to play music by:
1) enabling the home assistant media player provider
2) adding the onju speaker in that media player provider
3) setting the onju speaker to lossy mp3 in Music Assistant.
Screenshots attached.
![2024-03-09_16-01-25](https://github.com/justLV/onju-voice/assets/8059460/cd794cbb-d5a5-427f-a844-b466e881d2e5)
![2024-03-09_16-02-44](https://github.com/justLV/onju-voice/assets/8059460/5f0aa960-17f8-41d5-8b28-760b7050de4d)
![2024-03-09_16-03-26](https://github.com/justLV/onju-voice/assets/8059460/b375c657-1769-4c39-be7d-f69cb651dc38)

**Comment by justLV** [comment]
Closing, also not relevant to this project
