### ISSUE TITLE
[REQUEST] Temperature Sensor (BME280)?

### ISSUE THREAD

**Issue by MRebe** [justLV/onju-voice#53]
Hi JustLV and congratulations for the amazing job!
Looking at the pcb it seems like there is space to add something usefull, do you think a sensor for temperature (like the BME280) could fit? It would maybe need some adjustment due to the enclosured space of course, but add a thermometer could be very usefull in the home assistant world

**Comment by justLV** [comment]
If you're able to add or edit the ECAD feel free to and make a PR!

SGP30 or similar may be helpful for a home product. The focus of this was originally just voice so I didn't consider much other scope creep.
